
spool RE_ORG_VALIDATE.log
set time on;
set timing on;
SET SERVEROUTPUT ON SIZE 100000;
DECLARE
OT1 VARCHAR2(20);
TB1 VARCHAR2(32);
OI1 VARCHAR2(20);
ID1 VARCHAR2(32);
ddl_qry VARCHAR2(650);


CURSOR TBL1 IS
select owner,table_name from dba_tables where table_name IN ('FMS_TM_QUOTES_HEADER' );


CURSOR IDX1 IS
select owner,INDEX_NAME from DBA_INDEXES where TABLE_NAME=TB1 and TABLE_owner=OT1 and INDEX_TYPE <> 'LOB';


BEGIN


OPEN TBL1;
loop
fetch TBL1 INTO OT1,TB1;
EXIT WHEN TBL1%NOTFOUND;
ddl_qry := 'ALTER TABLE '||OT1||'.'||TB1||' MOVE';
EXECUTE IMMEDIATE ddl_qry;
dbms_output.put_line('TABLE REORG FOR '||TB1||' COMPLETED');


OPEN IDX1;
loop
fetch IDX1 into OI1,ID1;
EXIT WHEN IDX1%NOTFOUND;
ddl_qry := 'ALTER INDEX '||OI1||'.'||ID1||' REBUILD';
EXECUTE IMMEDIATE ddl_qry;
dbms_output.put_line('INDEX REBUILD FOR '||ID1||' COMPLETED');
END LOOP;
close IDX1;


ddl_qry := 'BEGIN DBMS_STATS.GATHER_TABLE_STATS (OWNNAME => '''||OT1||''',TABNAME =>'''||TB1||''',ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE,METHOD_OPT => ''FOR ALL INDEXED COLUMNS SIZE SKEWONLY'',DEGREE => CEIL(DBMS_STATS.AUTO_DEGREE/2),GRANULARITY => ''ALL'',NO_INVALIDATE => FALSE,CASCADE => TRUE); END;';
EXECUTE IMMEDIATE ddl_qry;
dbms_output.put_line('GATHER STATS FOR '||TB1||' COMPLETED');


END LOOP;


CLOSE TBL1;
END;
/
spool off

